apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - host: dtursunov.nvrbckdown.uz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: repo-5-95cd45c76-4dvds
                port:
                  number: 80
