apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: exam-davron
  labels:
    project: practice
    author: davron
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: exam-davron
  labels:
    project: practice
    author: davron
spec:
  containers:
    - name: nginx
      image: nginx
