apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: exam-davron
spec:
  limits:
    - type: Container
      default:
        cpu: "200m"
      defaultRequest:
        cpu: "100m"
      max:
        cpu: "1"
      min:
        cpu: "50m"
